import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, LockKeyhole, PlayCircle } from "lucide-react";
import { enrollInLearningPath, getLearningPathBySlug } from "@/app/actions/learning-paths";

export const dynamic = "force-dynamic";

export default async function LearningPathDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const path = await getLearningPathBySlug(slug);
  if (!path) notFound();
  const items = path.items;
  const totalJp = items.reduce((sum, item) => sum + Number(item.jp || 0), 0);
  const averageProgress = items.length ? Math.round(items.reduce((sum, item) => sum + Number(item.progress || 0), 0) / items.length) : 0;
  return (
    <main className="min-h-screen bg-oxford-50 dark:bg-oxford-950">
      <section className="bg-oxford-950 px-5 py-14 text-white"><div className="mx-auto max-w-6xl"><Link href="/paths" className="text-sm font-bold text-gold-400">← Semua learning path</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_320px]"><div><div className="mb-4 flex items-center gap-2 text-sm font-bold text-oxford-300"><span className="rounded-full bg-white/10 px-3 py-1">{String(path.visibility) === "private" ? "Privat" : "Publik"}</span><span>Disusun oleh {String(path.creatorName)}</span></div><h1 className="text-4xl font-bold leading-tight md:text-5xl">{String(path.title)}</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-oxford-300">{String(path.description || "Program pembelajaran terstruktur.")}</p><div className="mt-7 flex flex-wrap gap-5 text-sm font-semibold"><span className="inline-flex items-center gap-2"><BookOpen size={18} className="text-gold-400" /> {items.length} kursus</span><span className="inline-flex items-center gap-2"><Clock3 size={18} className="text-gold-400" /> {totalJp} JP</span></div></div><aside className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur"><p className="text-sm text-oxford-300">Progres keseluruhan</p><p className="mt-2 text-4xl font-bold">{averageProgress}%</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gold-400" style={{ width: `${averageProgress}%` }} /></div>{path.assignmentId ? <Link href={items[0] ? `/courses/${String(items[0].courseId)}` : "/paths"} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gold-500 px-4 py-3 font-bold text-oxford-950"><PlayCircle size={19} /> Lanjutkan belajar</Link> : path.isAuthenticated && String(path.visibility) === "public" ? <form action={enrollInLearningPath} className="mt-6"><input type="hidden" name="pathId" value={String(path.id)} /><button className="w-full rounded-xl bg-gold-500 px-4 py-3 font-bold text-oxford-950">Ikuti jalur ini</button></form> : path.isAuthenticated ? <p className="mt-6 flex items-center gap-2 rounded-xl bg-white/10 p-3 text-sm"><LockKeyhole size={17} /> Menunggu penugasan admin.</p> : <Link href={`/login?next=/paths/${slug}`} className="mt-6 block rounded-xl bg-gold-500 px-4 py-3 text-center font-bold text-oxford-950">Masuk untuk mengikuti</Link>}</aside></div></div></section>
      <section className="mx-auto max-w-4xl px-5 py-12"><div className="mb-7"><p className="text-sm font-bold uppercase tracking-widest text-gold-600">Kurikulum</p><h2 className="mt-2 text-2xl font-bold text-oxford-950 dark:text-white">Urutan pembelajaran</h2></div><div className="space-y-4">{items.map((item, index) => { const enrolled = Boolean(item.enrollmentStatus); const complete = String(item.enrollmentStatus) === "completed"; return <article key={String(item.id)} className="flex gap-4 rounded-2xl border border-oxford-200 bg-white p-5 dark:border-oxford-800 dark:bg-[#161B2A]"><div className={`flex size-11 shrink-0 items-center justify-center rounded-full font-bold ${complete ? "bg-emerald-100 text-emerald-700" : "bg-oxford-100 text-oxford-700 dark:bg-oxford-800 dark:text-white"}`}>{complete ? <CheckCircle2 size={22} /> : index + 1}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-bold text-oxford-950 dark:text-white">{String(item.title)}</h3><p className="mt-1 text-sm text-oxford-500">{String(item.category || "Kursus")} · {Number(item.jp || 0)} JP · {String(item.level || "Semua tingkat")}</p></div>{enrolled ? <Link href={`/courses/${String(item.courseId)}`} className="inline-flex items-center gap-1 text-sm font-bold text-blue-700 dark:text-blue-300">Buka <ArrowRight size={15} /></Link> : <span className="text-xs font-bold text-oxford-400">Daftar ke jalur untuk membuka</span>}</div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-oxford-100 dark:bg-oxford-800"><div className="h-full bg-emerald-500" style={{ width: `${Number(item.progress || 0)}%` }} /></div></div></article>; })}</div>
      </section>
    </main>
  );
}
