import Link from "next/link";
import { ArrowRight, CheckCircle2, GitBranch } from "lucide-react";
import { getMyLearningPaths } from "@/app/actions/learning-paths";

export const dynamic = "force-dynamic";

export default async function MyLearningPathsPage() {
  const paths = await getMyLearningPaths();
  return <main className="min-h-screen bg-oxford-50 px-5 py-10 dark:bg-oxford-950 md:px-10"><div className="mx-auto max-w-6xl"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-widest text-gold-600">Dashboard peserta</p><h1 className="mt-2 text-3xl font-bold text-oxford-950 dark:text-white">Learning path saya</h1><p className="mt-2 text-oxford-600 dark:text-oxford-300">Pantau jalur mandiri dan penugasan dari organisasi.</p></div><div className="grid gap-5 md:grid-cols-2">{paths.map(path => <article key={String(path.id)} className="rounded-2xl border border-oxford-200 bg-white p-6 dark:border-oxford-800 dark:bg-[#161B2A]"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-blue-700 dark:text-blue-300"><GitBranch size={16} /> {String(path.assignmentType) === "assigned" ? "Ditugaskan" : "Mandiri"}</span>{path.completedAt && <span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700"><CheckCircle2 size={15} /> Selesai</span>}</div><h2 className="mt-4 text-xl font-bold text-oxford-950 dark:text-white">{String(path.title)}</h2><p className="mt-2 line-clamp-2 text-sm text-oxford-600 dark:text-oxford-300">{String(path.description || "Program pembelajaran terstruktur.")}</p><div className="mt-5 flex justify-between text-sm"><span>{Number(path.courseCount)} kursus</span><strong>{Number(path.progress)}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-oxford-100 dark:bg-oxford-800"><div className="h-full rounded-full bg-gold-500" style={{ width: `${Number(path.progress)}%` }} /></div>{path.dueAt && <p className="mt-3 text-xs text-oxford-500">Tenggat: {new Date(String(path.dueAt)).toLocaleString("id-ID")}</p>}<Link href={`/paths/${String(path.slug)}`} className="mt-5 inline-flex items-center gap-2 font-bold text-blue-700 dark:text-blue-300">Buka jalur <ArrowRight size={17} /></Link></article>)}{paths.length === 0 && <div className="rounded-2xl border border-dashed border-oxford-300 p-12 text-center text-oxford-500 md:col-span-2"><p>Belum ada learning path.</p><Link href="/paths" className="mt-3 inline-block font-bold text-blue-700">Jelajahi jalur publik</Link></div>}</div></div></main>;
}
